"""empty message

Revision ID: 009768e7ec2a
Revises: c601ea8b699f
Create Date: 2021-03-24 18:14:59.163512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009768e7ec2a'
down_revision = 'c601ea8b699f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
